resources:
  - name: Upload
    type: IncomingWebhook
    configuration:
      webhookName: Upload_int

pipelines:
  - name: ExamplePipeline
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: Upload
      execution:
          onExecute:
            - echo "$res_MyIncomingWebhookResource_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"
