resources:
  - name: Upload
    type: IncomingWebhook
    configuration:
      webhookName: Upload_int

pipelines:
  - name: ExamplePipeline1
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: Upload
      execution:
          onExecute:
            - echo "job triggered by resource-> $step_triggered_by_resource_name"
            - echo "$res_Upload_payload" | jq '.' > payload.json
            - read_json payload.json "data.name" > name
            - repo_key=$(read_json payload.json "data.repo_key")
            - name=$(read_json payload.json "data.name")
            - read_json payload.json "data.repo_key" 
            - echo "JFrog CLI $value1"
            - curl -fL https://install-cli.jfrog.io | sh
            - jfrog config add Art12 --url=https://muddanajv.jfrog.io/ --user=sandeep --password=Password123 --enc-password=false --interactive=false
            - jf rt dl "$repo_key/$name"
            - pwd
            - ls
            - wget https://aka.ms/downloadazcopy-v10-linux
            - tar -xvf downloadazcopy-v10-linux
            - sudo rm -f /usr/bin/azcopy
            - sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
            - sudo chmod 755 /usr/bin/azcopy
            - rm -f downloadazcopy-v10-linux
            - rm -rf ./azcopy_linux_amd64_*/
            - azcopy copy '$name' 'https://sandeepa.file.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-04-06T22:35:38Z&st=2022-04-06T14:35:38Z&spr=https&sig=H%2FGLPQ7sjTb5LtA26ZUk0myBfxFW0cKSzApyWTW0y8s%3D'

            

