resources:
  - name: Upload
    type: IncomingWebhook
    configuration:
      webhookName: Upload_int

pipelines:
  - name: ExamplePipeline1
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: Upload
      execution:
          onExecute:
            - echo "job triggered by resource-> $step_triggered_by_resource_name"
            - echo "$res_Upload_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"
