resources:
  - name: Upload
    type: IncomingWebhook
    configuration:
      webhookName: Upload_int
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: Pipelinescantest
      fileLocation: example-repo-local/ 
      fileName: bs_result.txt # optional

pipelines:
  - name: ExamplePipeline1
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: Upload
      execution:
          onExecute:
            - echo "job triggered by resource-> $step_triggered_by_resource_name"
            - echo "$res_Upload_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"
            
  - name: uploadArtifactPipeline
    steps:
      - name: uploadArtifactStep
        type: UploadArtifact
        configuration:
          targetPath: k-npm-local/bs_result.txt
          integrations:
            - name: Pipelinescantest
          outputResources:
            - name: RemoteFile_1
