resources:
  - name: Upload
    type: IncomingWebhook
    configuration:
      webhookName: Upload_int

pipelines:
  - name: ExamplePipeline1
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: Upload
      execution:
          onExecute:
            - echo "job triggered by resource-> $step_triggered_by_resource_name"
            - echo "$res_Upload_payload" | jq '.' > payload.json
            - add_run_variables name=read_json payload.json "data.name"
            - read_json payload.json "data.repo_key" > "repo_key"
            - echo "JFrog CLI $name ---  name"
            - curl -fL https://install-cli.jfrog.io | sh
            - jfrog config add Art12 --url=https://muddanajv.jfrog.io/ --user=sandeep --password=Password123 --enc-password=false --interactive=false
            - jf rt dl "repo_key/name"
            

