resources:
  - name: UploadRes
    type: IncomingWebhook
    configuration:
      webhookName: Upload_int

pipelines:
  - name: ExamplePipeline1
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: UploadRes
      execution:
          onExecute:
            - echo "$res_UploadRes_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"
